- name: check if kubernetes has already been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat
- name: initialize kubernetes controlplane with kubeadm init
  command: "kubeadm init --pod-network-cidr={{ kubernetes_pod_network.cidr }}"
  when: not kubernetes_init_stat.stat.exists
  register: kubeadm_init
- name: print init output to screen
  debug:
    msg: "{{ kubeadm_init.stdout_lines | select('search', 'kubeadm join') | first }}"
  when: not kubernetes_init_stat.stat.exists
- name: ensure .kube directory exists
  file:
    path: ~/.kube
    state: directory
    mode: 0755
- name: symlink the kubectl admin.conf to ~/.kube/config
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644
- name: configure calico networking
  command: "kubectl apply -f {{ kubernetes_calico_manifest_file }}"
  register: calico_result
  changed_when: "'created' in calico_result.stdout"
  when: kubernetes_pod_network.cni == 'calico'
  until: calico_result is not failed
  retries: 12
  delay: 5
- name: get kubeadm join command from controlplane
  command: "kubeadm token create --print-join-command"
  register: kubeadm_token_create
- name: print created token
  debug:
    msg: "{{ kubeadm_token_create.stdout }}"
- name: set kubeadm join command globally
  set_fact:
    kubernetes_join_command: "{{ kubeadm_token_create.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"
